public enum UnitTag{
    ROCKET_WORKER,
    FACTORY_WORKER,
    EARTH_FARM_WORKER,
    MARS_FARM_WORKER,
    EARTH_DEFENSE_KNIGHT,
    MARS_DEFENSE_KNIGHT,
    EARTH_ATTACK_KNIGHT,
    MARS_ATTACK_KNIGHT,
    EARTH_MAGE,
    MARS_MAGE,
    EARTH_SCOUT_RANGER,
    MARS_SCOUT_RANGER,
    SNIPER_RANGER,
    EARTH_HEALER,
    MARS_HEALER,
    NONE
}